/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:Gene_Builder:993507:
  appc.background(230);
} //_CODE_:Gene_Builder:993507:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:269991:
} //_CODE_:dropList1:269991:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:910330:
  alignment_amnt = 0;
  error_message = false;
  alignment_display = false;
  first_alignment_string = "";
  second_alignment_string = "";
  
  input_txt1 = "";
  input_txt2 = "";
  input_txt1 = textarea1.getText();
  input_txt2 = textarea2.getText();
  
  if (input_txt1.equals("") || input_txt2.equals("")) {
    error_message = true;
  }
  else {
    String[] input_list_1 = split(input_txt1, " ");
    String[] input_list_2 = split(input_txt2," ");
    for (int index = 0; index < input_list_1.length; index++) {
      if (input_list_1[index].equals("")) {}
      else {
        for (int i = 0; i < input_list_1[index].length(); i++) {
          int unicode_value = int(input_list_1[index].charAt(i));
          if (unicode_value == 65 || unicode_value == 67 || unicode_value == 71 || unicode_value == 84) {
            //println("1");
            first_alignment_string += input_list_1[index].charAt(i); 
          }
          else {}
        }
      }
    }
    for (int index = 0; index < input_list_2.length; index++) {
      if (input_list_2[index].equals("")) {}
      else {
        for (int i = 0; i < input_list_2[index].length(); i++) {
          int unicode_value = int(input_list_2[index].charAt(i));
          if (unicode_value == 65 || unicode_value == 67 || unicode_value == 71 || unicode_value == 84) {
            //println("2");
            second_alignment_string += input_list_2[index].charAt(i);
          }
          else {}
        }
      }
    }
    
    
    alignment_amnt = Nucleotides.amount_of_alignments(first_alignment_string, second_alignment_string);
    ArrayList<String[]> all_align = Nucleotides.align_list(second_alignment_string.length()-1, first_alignment_string.length()-1);
    for (String[] element: all_align) {
      printArray(element);
    }
    gene_pair = Nucleotides.account_fillers(all_align);
    compare_display = true;
    alignment_display = true;
    
  }
} //_CODE_:button1:910330:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:753770:
  alignment_amnt = 0;
  error_message = false;
  alignment_display = false;
  first_alignment_string = "";
  second_alignment_string = "";
  textarea1.setText("");
  textarea2.setText("");
} //_CODE_:button2:753770:

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:textarea1:845802:
} //_CODE_:textarea1:845802:

public void textarea2_change1(GTextArea source, GEvent event) { //_CODE_:textarea2:774808:
} //_CODE_:textarea2:774808:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:512677:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button3:512677:

public void shift_alignment_gene(GCustomSlider source, GEvent event) { //_CODE_:shift_alignment:855943:
  println("shift_alignment - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:shift_alignment:855943:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Gene_Builder = GWindow.getWindow(this, "Window title", 0, 0, 500, 500, JAVA2D);
  Gene_Builder.noLoop();
  Gene_Builder.setActionOnClose(G4P.KEEP_OPEN);
  Gene_Builder.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(Gene_Builder, 18, 12, 176, 24);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Enter first gene sequence here:");
  label1.setOpaque(false);
  label2 = new GLabel(Gene_Builder, 15, 288, 245, 29);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Is there a specific trait you would like to view?");
  label2.setOpaque(false);
  dropList1 = new GDropList(Gene_Builder, 13, 335, 160, 100, 4, 10);
  dropList1.setItems(loadStrings("list_269991"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  button1 = new GButton(Gene_Builder, 356, 408, 123, 77);
  button1.setText("Generate Alignments");
  button1.addEventHandler(this, "button1_click1");
  label3 = new GLabel(Gene_Builder, 281, 12, 195, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Enter second gene sequence here:");
  label3.setOpaque(false);
  button2 = new GButton(Gene_Builder, 375, 362, 80, 30);
  button2.setText("Reset All");
  button2.addEventHandler(this, "button2_click1");
  textarea1 = new GTextArea(Gene_Builder, 19, 51, 201, 159, G4P.SCROLLBARS_NONE);
  textarea1.setOpaque(true);
  textarea1.addEventHandler(this, "textarea1_change1");
  textarea2 = new GTextArea(Gene_Builder, 275, 49, 212, 161, G4P.SCROLLBARS_NONE);
  textarea2.setOpaque(true);
  textarea2.addEventHandler(this, "textarea2_change1");
  button3 = new GButton(Gene_Builder, 401, 298, 80, 30);
  button3.setText("Re-centre Alignment");
  button3.addEventHandler(this, "button3_click1");
  shift_alignment = new GCustomSlider(Gene_Builder, 352, 233, 100, 40, "grey_blue");
  shift_alignment.setLimits(0.5, 0.0, 1.0);
  shift_alignment.setNbrTicks(5);
  shift_alignment.setNumberFormat(G4P.DECIMAL, 2);
  shift_alignment.setOpaque(false);
  shift_alignment.addEventHandler(this, "shift_alignment_gene");
  Gene_Builder.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow Gene_Builder;
GLabel label1; 
GLabel label2; 
GDropList dropList1; 
GButton button1; 
GLabel label3; 
GButton button2; 
GTextArea textarea1; 
GTextArea textarea2; 
GButton button3; 
GCustomSlider shift_alignment; 
